http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec-bouncer:
          crowdsecLapiKey: '{{ env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY" }}'
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecMode: "stream"
          crowdsecDefaultDecisionOnCheckError: '{{ env "CROWDSEC_ON_ERROR" }}'
